dist: xenial
sudo: false
language: cpp
dist: bionic
python:
  - 3.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - pyenv install -l
  - pyenv install 3.7 -y
  - pyenv global 3.7
  - wget -qO- https://bootstrap.pypa.io/get-pip.py | python
  - python --version
  - python -m pip install -e .[dev]
  - python setup.py bdist_wheel
  - ls dist

  
