dist: bionic
sudo: false
language: cpp
python:
  - 3.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

jobs:
  include:
    - stage: installation
      script:
        - pyenv install -l
        - pyenv install 3.7 -f
        - pyenv global 3.7
        - wget -qO- https://bootstrap.pypa.io/get-pip.py | python
        - python --version
        - python -m pip install -e .[dev]
    - stage: deploy
      if: branch = master AND tag IS present
      script:
        - python setup.py bdist_wheel
        - ls dist
