os: linux
dist: bionic
language: cpp
python:
  - 3.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

jobs:
  include:
    - stage: test-cpp
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make test_constructor_comparison
        - make test_file_constructor
        - make test_variable_constructor
        - ./test_constructor_comparison
        - ./test_file_constructor
        - ./test_variable_constructor
    - stage: test-python
      script:
        - pyenv global 3.7
        - python --version
        - wget -qO- https://bootstrap.pypa.io/get-pip.py | python
        - python -m pip install -e .[dev]
        - cd tests
        - python pyWaveTest.py
    - stage: python-deploy
      if: branch = master AND tag IS present
      script:
        - python setup.py bdist_wheel
        - ls dist
