dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - ls
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ..
  - make forward_test
  - make adjoint_test
  - ./forward_test
  - ./adjoint_test