dist: xenial
sudo: false
language: cpp
dist: bionic
python:
  - 3.7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - python3.7-dev

script:
  - wget -qO- https://bootstrap.pypa.io/get-pip.py | python3
  - python3 --version
  - ls
  - python3 setup.py bdist_wheel
  - ls dist

  
