dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - ls
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .. -DCMAKE_BUILD_TYPE=Release
  - make forward_test
  - ./forward_test ../tests/test_configurations/forward_configuration.ini
  - python --version
